package com.example.dentistryapp.ui.theme

import androidx.compose.ui.graphics.Color

val dentistryLightPrimary = Color(0xFF825500)
val dentistryLightOnPrimary = Color(0xFFFFFFFF)
val dentistryLightPrimaryContainer = Color(0xFFFFDDAE)
val dentistryLightOnPrimaryContainer = Color(0xFF2A1800)
val dentistryLightSecondary = Color(0xFF6F5B40)
val dentistryLightOnSecondary = Color(0xFFFFFFFF)
val dentistryLightSecondaryContainer = Color(0xFFFADEBC)
val dentistryLightOnSecondaryContainer = Color(0xFF271904)
val dentistryLightTertiary = Color(0xFF516440)
val dentistryLightOnTertiary = Color(0xFFFFFFFF)
val dentistryLightTertiaryContainer = Color(0xFFD3EABC)
val dentistryLightOnTertiaryContainer = Color(0xFF102004)
val dentistryLightError = Color(0xFFBA1B1B)
val dentistryLightErrorContainer = Color(0xFFFFDAD4)
val dentistryLightOnError = Color(0xFFFFFFFF)
val dentistryLightOnErrorContainer = Color(0xFF410001)
val dentistryLightBackground = Color(0xFFFCFCFC)
val dentistryLightOnBackground = Color(0xFF1F1B16)
val dentistryLightSurface = Color(0xFFFCFCFC)
val dentistryLightOnSurface = Color(0xFF1F1B16)
val dentistryLightSurfaceVariant = Color(0xFFF0E0CF)
val dentistryLightOnSurfaceVariant = Color(0xFF4F4539)
val dentistryLightOutline = Color(0xFF817567)
val dentistryLightInverseOnSurface = Color(0xFFF9EFE6)
val dentistryLightInverseSurface = Color(0xFF34302A)
val dentistryLightPrimaryInverse = Color(0xFFFFB945)

val dentistryDarkPrimary = Color(0xFFFFB945)
val dentistryDarkOnPrimary = Color(0xFF452B00)
val dentistryDarkPrimaryContainer = Color(0xFF624000)
val dentistryDarkOnPrimaryContainer = Color(0xFFFFDDAE)
val dentistryDarkSecondary = Color(0xFFDDC3A2)
val dentistryDarkOnSecondary = Color(0xFF3E2E16)
val dentistryDarkSecondaryContainer = Color(0xFF56442B)
val dentistryDarkOnSecondaryContainer = Color(0xFFFADEBC)
val dentistryDarkTertiary = Color(0xFFB8CEA2)
val dentistryDarkOnTertiary = Color(0xFF243516)
val dentistryDarkTertiaryContainer = Color(0xFF3A4C2B)
val dentistryDarkOnTertiaryContainer = Color(0xFFD3EABC)
val dentistryDarkError = Color(0xFFFFB4A9)
val dentistryDarkErrorContainer = Color(0xFF930006)
val dentistryDarkOnError = Color(0xFF680003)
val dentistryDarkOnErrorContainer = Color(0xFFFFDAD4)
val dentistryDarkBackground = Color(0xFF1F1B16)
val dentistryDarkOnBackground = Color(0xFFEAE1D9)
val dentistryDarkSurface = Color(0xFF1F1B16)
val dentistryDarkOnSurface = Color(0xFFEAE1D9)
val dentistryDarkSurfaceVariant = Color(0xFF4F4539)
val dentistryDarkOnSurfaceVariant = Color(0xFFD3C4B4)
val dentistryDarkOutline = Color(0xFF9C8F80)
val dentistryDarkInverseOnSurface = Color(0xFF32281A)
val dentistryDarkInverseSurface = Color(0xFFEAE1D9)
val dentistryDarkPrimaryInverse = Color(0xFF624000)